### ISSUE TITLE
Panic when restoring inside Alpine container on AWS (but not DO...)

### ISSUE THREAD

**Issue by davehancock** [opinari/freighter#18]
core@ip-10-0-1-188 ~ $ docker logs -f 09139a0584c1
Cert Type: full-ssl-certs
Restoring SSL Certs....
   ____        _      __   __         
  / __/______ (_)__ _/ /  / /____ ____
 / _// __/ -_) / _ `/ _ \/ __/ -_) __/
/_/ /_/  \__/_/\_, /_//_/\__/\__/_/   
              /___/                   
2017/02/06 23:47:15 Performing Restore
2017/02/06 23:47:15 Downloading file from: '/full-ssl-certs.tar.gz' to: '/etc/ssl'
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8172a17]

goroutine 1 [running]:
panic(0x839c920, 0x18820030)
	/home/travis/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:481 +0x326
github.com/opinari/freighter/dropbox.DownloadFile(0xffc97f03, 0x8, 0xffc97eda, 0x16, 0x0, 0x0, 0xf7733858, 0x188fe580)
	/home/travis/gopath/src/github.com/opinari/freighter/dropbox/dropbox.go:80 +0xdf7
github.com/opinari/freighter/client.RestoreFile(0xffc97f03, 0x8, 0xffc97eda, 0x16)
	/home/travis/gopath/src/github.com/opinari/freighter/client/client.go:19 +0x6c
main.runCLI()
	/home/travis/gopath/src/github.com/opinari/freighter/main.go:50 +0xdfd
main.main()
	/home/travis/gopath/src/github.com/opinari/freighter/main.go:20 +0x67
Restored SSL Backup!
2017/02/06 23:47:36 [emerg] 10#10: BIO_new_file("/etc/ssl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] BIO_new_file("/etc/ssl/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

**Comment by davehancock** [comment]
Fixed - Small tweaks made, main fix was putting defers in correct place. This issue was hiding a genuine error resolving the DNS for dropbox which is to do with Docker embedded DNS and a fallback to /etc/resolve
